version: "3"

services:

  queue_mgr:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    hostname: "queueMgrServ"
    image: weblinuxgame/queue-mgr:${IMG_VERSION:-v0.1.0}
    restart: always
    volumes:
      - ./.env:/app/.env:ro
      - /etc/localtime:/etc/localtime:ro
      - ./.docker/config:/app/config:ro
      - ./.docker/logs:/app/logs:rw
    ports:
      - "18023:80"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
