basePath: /queue_mgr
definitions:
  entity.JsonData:
    properties:
      code:
        type: integer
      info:
        items:
          $ref: '#/definitions/entity.KvMap'
        type: array
      msg:
        type: string
    type: object
  entity.JsonResponse:
    properties:
      data:
        $ref: '#/definitions/entity.JsonData'
        description: Data
      ret:
        description: httpCode
        type: integer
    type: object
  entity.KvMap:
    additionalProperties: true
    type: object
host: localhost:81
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: app队列管理服务发服务
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: QueueMgrServ
  version: "1.0"
paths:
  /bind:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: bind queue consumer
      parameters:
      - description: access jwt token
        in: header
        name: Authorization
        required: true
        type: string
      - description: consumer/消费器名
        in: formData
        name: consumer
        type: string
      - description: queue/队列名
        in: formData
        name: queue
        type: string
      - description: properties/绑定消费器相关参数(json)
        in: formData
        name: properties
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.JsonResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.JsonResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entity.JsonResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.JsonResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/entity.JsonResponse'
      summary: 给队列绑定消费协程
      tags:
      - QueueMgrServ
  /consumer/create:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: create queue consumer
      parameters:
      - description: access jwt token
        in: header
        name: Authorization
        required: true
        type: string
      - description: consumer/消费器名
        in: formData
        name: consumer
        required: true
        type: string
      - description: type/消费器类型
        enum:
        - '"FastCGI"'
        - '"Native"'
        - '"Shell"'
        - '"Api"'
        - '"Grpc"'
        - '"Proxy"'
        - '"Plugins"'
        in: formData
        name: type
        required: true
        type: string
      - description: properties/消费器相关参数(json)
        in: formData
        name: properties
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.JsonResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.JsonResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entity.JsonResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.JsonResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/entity.JsonResponse'
      summary: 创建队列消费器
      tags:
      - QueueMgrServ
  /consumers:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: query queue consumer lists
      parameters:
      - description: access jwt token
        in: header
        name: Authorization
        required: true
        type: string
      - default: 1
        description: page/页码
        in: formData
        name: page
        type: integer
      - default: 10
        description: count/分页量
        in: query
        name: count
        type: integer
      - description: state/消费进程状态
        enum:
        - 0
        - 1
        - 2
        - 3
        in: query
        name: state
        type: integer
      - default: '"created_at:desc"'
        description: sort/排序参数
        in: query
        name: sort
        type: string
      - description: 'name/限定队列名(模糊匹配eg: test*)'
        in: query
        name: queue
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.JsonResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.JsonResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entity.JsonResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.JsonResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/entity.JsonResponse'
      summary: 罗列消费队列信息
      tags:
      - QueueMgrServ
  /metrics:
    get:
      description: prometheus Metrics
      produces:
      - text/plain
      summary: export prometheus metrics
      tags:
      - QueueMgrServ
  /queue/create:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: add queue  info
      parameters:
      - description: access jwt token
        in: header
        name: Authorization
        required: true
        type: string
      - description: queue/队列名
        in: formData
        name: queue
        required: true
        type: string
      - description: queue/队列链接驱动器类型
        enum:
        - '"AMQP"'
        - '"MQTT"'
        - '"HTTP"'
        - '"WS"'
        - '"PLUGINS"'
        in: formData
        name: driver
        required: true
        type: string
      - description: properties/可消费队列相关参数(json)
        in: formData
        name: properties
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.JsonResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.JsonResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entity.JsonResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.JsonResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/entity.JsonResponse'
      summary: 创建可消费队列信息
      tags:
      - QueueMgrServ
  /routers:
    get:
      description: List Service Api Routers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.KvMap'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.KvMap'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entity.KvMap'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.KvMap'
        default:
          description: ""
          schema:
            $ref: '#/definitions/entity.KvMap'
      summary: 罗列服务接口列表
      tags:
      - QueueMgrServ
  /state:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: query queue consumer state
      parameters:
      - description: access jwt token
        in: header
        name: Authorization
        required: true
        type: string
      - description: queue/消费队列名
        in: query
        name: queue
        required: true
        type: string
      - description: tag/消费进程标签
        in: query
        name: tag
        type: string
      - description: state/消费进程状态
        enum:
        - 1
        - 2
        - 3
        in: query
        name: state
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.JsonResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.JsonResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entity.JsonResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.JsonResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/entity.JsonResponse'
      summary: 查询队列消费器状态
      tags:
      - QueueMgrServ
  /state/update:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: change queue consumer state or processor number
      parameters:
      - description: access jwt token
        in: header
        name: Authorization
        required: true
        type: string
      - description: queue/消费队列名
        in: formData
        name: queue
        required: true
        type: string
      - description: state/消费进程状态
        enum:
        - 1
        - 2
        - 3
        in: formData
        name: state
        type: integer
      - description: tag/消费进程标签
        in: formData
        name: tag
        type: string
      - default: 0
        description: scale/消费队列协程数扩缩容
        in: formData
        name: scale
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.JsonResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.JsonResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entity.JsonResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.JsonResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/entity.JsonResponse'
      summary: 控制队列消费器状态
      tags:
      - QueueMgrServ
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
  BasicAuth:
    type: basic
  OAuth2AccessCode:
    authorizationUrl: https://example.com/oauth/authorize
    flow: accessCode
    scopes:
      admin: ' Grants read and write access to administrative information'
    tokenUrl: https://example.com/oauth/token
    type: oauth2
  OAuth2Application:
    flow: application
    scopes:
      admin: ' Grants read and write access to administrative information'
      write: ' Grants write access'
    tokenUrl: https://example.com/oauth/token
    type: oauth2
  OAuth2Implicit:
    authorizationUrl: https://example.com/oauth/authorize
    flow: implicit
    scopes:
      admin: ' Grants read and write access to administrative information'
      write: ' Grants write access'
    type: oauth2
  OAuth2Password:
    flow: password
    scopes:
      admin: ' Grants read and write access to administrative information'
      read: ' Grants read access'
      write: ' Grants write access'
    tokenUrl: https://example.com/oauth/token
    type: oauth2
swagger: "2.0"
tags:
- description: 'app队列管理服务发服务接口集合 服务路由前缀: /queue_mgr/, jwt scope: queueMgrServ'
  name: QueueMgrServ
x-extension-openapi:
  name: QueueMgrServ
